title: "Adventures in Cloudland"
author:
  name: Lukasz Kozubal
  
remote_theme: jekyll/minima
plugins:
  - jemoji  
  - jekyll-sitemap  

minima:
  skin: auto
  social_links: 
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/lkozubal" }
    - { platform: github,  user_url: "https://github.com/lucas-ko" }
